language: bash
sudo: required
services:
  - docker

before_install:
  - sudo apt-get install python-dev
install:
  - sudo pip install ansible
  - sudo pip install ansible-container
before_script:
script:
  - sudo ansible-container --var-file vars.yml build
after_success:
after_failure:
after_script:
