version: "2"
services:
  # Add your containers here, specifying the base image you want to build from
  # For example:
  #
  app:
    image: rails
    ports:
      - "30000:3000"
    command: ['bundle', 'exec','rails', 's','-p','3000','-b' , '0.0.0.0']
    working_dir: "{{ deploy_dir }}/rasr"
    environment:
      DEVISE_SECRET_KEY_TEST: test
      GLIBRARY_USERNAME: "{{ glibrary_username }}"
      GLIBRARY_PASSWORD: "{{ glibrary_password }}"
    dev_overrides:
      environment:
        - "DEBUG=1"
  db:
    image: "{{ docker_sql_image }}"
    ports:
      - "3306:3306"
    command: docker-entrypoint.sh mysqld
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
  api_server:
    image: tomcat:8.5-jre8
    command: ["catalina.sh","run"]
    ports:
      - 8888:8080



registries:
  docker:
    url: https://hub.docker.com
    namespace: /u/aaroc
  quay:
    url: https://quay.io
    namespace: aaroc
