---
# Where will the rasr app be deployed
deploy_dir: /opt/deploy/

mysql_python_package:
  RedHat: MySQL-python
  Debian: python-mysqldb
# What base image will you be using for the sql db
docker_sql_image: "mysql:5.5"
# What name do you want to give the running container ?
db_container_name: "fg-db"
# root password of the db - put this in your group_vars and then in a vault in production
db_root_password: "changeme"
# API Server db config
# API Server user name and password - should be kept in group_vars
api_db_username: "fgapiserver"
api_db_userpass: "wo6YqaSCp-Ur-Nma4kPp2qJOMXhW_bUg"
api_db_name: fgapiserver
# where will we store the SQL data ?
sql_data_dir: /tmp/fgapi-server-db-data/

# API installation path
prereq:
  RedHat:
    - mysql-devel
  Debian:
    - libmysqlclient-dev
extra_pips:
  - "urllib3[secure]"
  - flask_login
